name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      if: ${{ env.PUSH_PACKAGES }}
      run: dotnet publish
    - name: Upload artifacts
      if: ${{ env.PUSH_PACKAGES }}
      uses: actions/upload-artifact@v2
      with:
        name: WebPrefer.SlackBot
        path: /home/runner/work/WebPrefer.SlackBot/WebPrefer.SlackBot/WebPrefer.SlackBot/bin/Debug/net5.0/publish/
