name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEPLOY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      AZURE_WEBAPP_NAME: WebPreferSlackBot

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      if: ${{ env.DEPLOY }}
      run: |
        dotnet publish -c Release -o webpreferslackbot 
    - name: Deploy
      if: ${{ env.DEPLOY }}
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './webpreferslackbot'
    
